stages:
  - test
  - build
  - deploy
  - notify

test:
  stage: test
  image: python:3.8.3-alpine
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  # Replication is ok here I think.
  script:
    - apk update
    - apk add --update --no-cache postgresql-dev gcc libc-dev linux-headers postgresql-dev musl-dev zlib-dev
    - apk add --update --no-cache postgresql-dev python3-dev libpq
    - apk add --update --no-cache postgresql-dev graphviz-dev jpeg-dev
    - pip3 install -r requirements.txt
    - pytest

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
  script:
    - case "$CI_COMMIT_BRANCH" in (master) TAG="stable"  ;; (dev) TAG="latest"  ;; (*) exit 1 ;; esac
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 -w 0)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:$TAG"
    - echo "${CI_REGISTRY_IMAGE}:$TAG"

deploy:
  stage: deploy
  image: alpine/helm:3.9.4
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'master'
      when: manual
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == 'dev'
  environment:
    name: review/$CI_COMMIT_REF_SLUG
  script:
    - case "$CI_COMMIT_BRANCH" in (master) TAG="stable"        ;; (dev) TAG="latest"          ;; (*) exit 1 ;; esac
    - case "$CI_COMMIT_BRANCH" in (master) NAMESPACE="prd"     ;; (dev) NAMESPACE="dev"       ;; (*) exit 1 ;; esac
    - helm upgrade --install -n $NAMESPACE test-app-backend chart --set image.tag=$TAG


notify:
  stage: notify
  image: curlimages/curl:7.86.0 
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
  script:
    - |
      curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, backend!"}' https://hooks.slack.com/services/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
