version: '3.8'

networks:
  test-app-network:
    driver: bridge

services:
  test-app-backend:
    container_name: test-app-backend
    # image: test-app-backend:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: emivespa/test-app-backend:latest
    depends_on:
      - test-app-db
    env_file:
      - ./env
    networks:
      - test-app-network
    ports:
      - "8000:8000" # == RUNSERVER_PORT @ env_file == API_SERVER @ $front/src/config/contstant.js
    command: python manage.py flush --no-input
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:"$RUNSERVER_PORT"
  test-app-db:
    container_name: test-app-db
    image: postgres:15.1-alpine3.16
    env_file:
      - ./env.postgres
    expose:
      - 5432
    networks:
      - test-app-network

